import 'package:buffalo_thai/model/buffalo_clip_model.dart';
import 'package:buffalo_thai/model/competitions_model.dart';
import 'package:buffalo_thai/model/farm_model.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:buffalo_thai/model/buffalo_image_model.dart';

part 'buffalo_model.g.dart'; // This will be generated by json_serializable

@JsonSerializable(explicitToJson: true)
class BuffaloModel {
  @JsonKey(name: 'buffaloId')
  final int id;
  @JsonKey(name: 'name', defaultValue: '')
  final String name;
  @JsonKey(name: 'birthDate')
  final DateTime? birthDate;
  @JsonKey(name: 'birthMethod', defaultValue: '')
  final String birthMethod;
  @JsonKey(name: 'gender', defaultValue: '')
  final String gender;
  @JsonKey(name: 'color', defaultValue: '')
  final String color;

  @JsonKey(name: 'fatherId', defaultValue: null)
  final int? fatherId;
  @JsonKey(name: 'fatherName', defaultValue: '')
  final String fatherName;
  @JsonKey(name: 'fatherFarmName', defaultValue: '')
  final String fatherFarmName;

  @JsonKey(name: 'fatherGrandfatherId', defaultValue: null)
  final int? fatherGrandfatherId;
  @JsonKey(name: 'fatherGrandfatherName', defaultValue: '')
  final String fatherGrandfatherName;
  @JsonKey(name: 'fatherGrandfatherFarmName', defaultValue: '')
  final String fatherGrandfatherFarmName;

  @JsonKey(name: 'fatherGrandmotherId', defaultValue: null)
  final int? fatherGrandmotherId;
  @JsonKey(name: 'fatherGrandmotherName', defaultValue: '')
  final String fatherGrandmotherName;
  @JsonKey(name: 'fatherGrandmotherFarmName', defaultValue: '')
  final String fatherGrandmotherFarmName;

  @JsonKey(name: 'motherId', defaultValue: null)
  final int? motherId;
  @JsonKey(name: 'motherName', defaultValue: '')
  final String motherName;
  @JsonKey(name: 'motherFarmName', defaultValue: '')
  final String motherFarmName;

  @JsonKey(name: 'motherGrandfatherId', defaultValue: null)
  final int? motherGrandfatherId;
  @JsonKey(name: 'motherGrandfatherName', defaultValue: '')
  final String motherGrandfatherName;
  @JsonKey(name: 'motherGrandfatherFarmName', defaultValue: '')
  final String motherGrandfatherFarmName;

  @JsonKey(name: 'motherGrandmotherId', defaultValue: null)
  final int? motherGrandmotherId;
  @JsonKey(name: 'motherGrandmotherName', defaultValue: '')
  final String motherGrandmotherName;
  @JsonKey(name: 'motherGrandmotherFarmName', defaultValue: '')
  final String motherGrandmotherFarmName;

  @JsonKey(name: 'fatherGreatGrandfatherId', defaultValue: null)
  final int? fatherGreatGrandfatherId;
  @JsonKey(name: 'fatherGreatGrandfatherName', defaultValue: '')
  final String fatherGreatGrandfatherName;
  @JsonKey(name: 'fatherGreatGrandfatherFarmName', defaultValue: '')
  final String fatherGreatGrandfatherFarmName;

  @JsonKey(name: 'fatherGreatGrandmotherId', defaultValue: null)
  final int? fatherGreatGrandmotherId;
  @JsonKey(name: 'fatherGreatGrandmotherName', defaultValue: '')
  final String fatherGreatGrandmotherName;
  @JsonKey(name: 'fatherGreatGrandmotherFarmName', defaultValue: '')
  final String fatherGreatGrandmotherFarmName;

  @JsonKey(name: 'motherGreatGrandfatherId', defaultValue: null)
  final int? motherGreatGrandfatherId;
  @JsonKey(name: 'motherGreatGrandfatherName', defaultValue: '')
  final String motherGreatGrandfatherName;
  @JsonKey(name: 'motherGreatGrandfatherFarmName', defaultValue: '')
  final String motherGreatGrandfatherFarmName;

  @JsonKey(name: 'motherGreatGrandmotherId', defaultValue: null)
  final int? motherGreatGrandmotherId;
  @JsonKey(name: 'motherGreatGrandmotherName', defaultValue: '')
  final String motherGreatGrandmotherName;
  @JsonKey(name: 'motherGreatGrandmotherFarmName', defaultValue: '')
  final String motherGreatGrandmotherFarmName;

  @JsonKey(name: 'buffaloStatus', defaultValue: '')
  final String buffaloStatus;
  @JsonKey(name: 'bornAt', defaultValue: '')
  final String? bornAt;

  @JsonKey(name: 'currentFarmId', defaultValue: null)
  final int? currentFarmId;
  @JsonKey(name: 'farmId')
  final int farmId;
  @JsonKey(name: 'createdAt')
  final DateTime createdAt;
  @JsonKey(name: 'updatedAt')
  final DateTime updatedAt;

  @JsonKey(name: 'farm')
  final FarmModel? farm;
  @JsonKey(name: 'currentFarm')
  final FarmModel? currentFarm;
  final BuffaloModel? father;
  final BuffaloModel? mother;
  final BuffaloModel? grandfather;
  final BuffaloModel? grandmother;
  final BuffaloModel? greatGrandfather;
  final BuffaloModel? greatGrandmother;

  @JsonKey(name: 'BuffaloImages', defaultValue: [])
  final List<BuffaloImageModel> buffaloImages;
  @JsonKey(name: 'BuffaloBreedingImages', defaultValue: [])
  final List<dynamic> buffaloBreedingImages;
  @JsonKey(name: 'BuffaloClips', defaultValue: [])
  final List<BuffaloClipModel> buffaloClips;
  @JsonKey(name: 'Histories', defaultValue: [])
  final List<dynamic> histories;
  @JsonKey(name: 'Competitions', defaultValue: [])
  final List<CompetitionsModel> competitions;

  BuffaloModel(
    this.fatherFarmName,
    this.fatherGrandfatherFarmName,
    this.fatherGrandmotherFarmName,
    this.motherFarmName,
    this.motherGrandfatherFarmName,
    this.motherGrandmotherFarmName,
    this.fatherGreatGrandfatherFarmName,
    this.fatherGreatGrandmotherFarmName,
    this.motherGreatGrandfatherFarmName,
    this.motherGreatGrandmotherFarmName, {
    required this.id,
    required this.name,
    required this.birthMethod,
    this.birthDate,
    this.fatherId,
    required this.fatherName,
    this.fatherGrandfatherId,
    required this.fatherGrandfatherName,
    this.fatherGrandmotherId,
    required this.fatherGrandmotherName,
    this.motherId,
    required this.motherName,
    this.motherGrandfatherId,
    required this.motherGrandfatherName,
    this.motherGrandmotherId,
    required this.motherGrandmotherName,
    this.fatherGreatGrandfatherId,
    required this.fatherGreatGrandfatherName,
    this.fatherGreatGrandmotherId,
    required this.fatherGreatGrandmotherName,
    this.motherGreatGrandfatherId,
    required this.motherGreatGrandfatherName,
    this.motherGreatGrandmotherId,
    required this.motherGreatGrandmotherName,
    required this.gender,
    required this.color,
    required this.buffaloStatus,
    this.bornAt,
    this.currentFarmId,
    required this.farmId,
    required this.createdAt,
    required this.updatedAt,
    this.farm,
    this.currentFarm,
    this.father,
    this.mother,
    this.grandfather,
    this.grandmother,
    this.greatGrandfather,
    this.greatGrandmother,
    this.buffaloImages = const [],
    this.buffaloBreedingImages = const [],
    this.buffaloClips = const [],
    this.histories = const [],
    this.competitions = const [],
  });

  factory BuffaloModel.fromJson(Map<String, dynamic> json) =>
      _$BuffaloModelFromJson(json);
  Map<String, dynamic> toJson() => _$BuffaloModelToJson(this);
}
