import 'package:buffalo_thai/model/farm_model.dart';
import 'package:json_annotation/json_annotation.dart';

part 'buffalo_model.g.dart'; // This will be generated by json_serializable

@JsonSerializable(explicitToJson: true)
class BuffaloModel {
  @JsonKey(name: 'buffaloId')
  final int id;
  final String name;
  @JsonKey(name: 'birthDate')
  final DateTime birthDate;
  @JsonKey(name: 'birthMethod')
  final String birthMethod;
  @JsonKey(name: 'fatherId')
  final int? fatherId;
  @JsonKey(name: 'motherId')
  final int? motherId;
  @JsonKey(name: 'grandfatherId')
  final int? grandfatherId;
  @JsonKey(name: 'grandmotherId')
  final int? grandmotherId;
  @JsonKey(name: 'greatGrandfatherId')
  final int? greatGrandfatherId;
  @JsonKey(name: 'greatGrandmotherId')
  final int? greatGrandmotherId;
  @JsonKey(name: 'currentFarmId')
  final int? currentFarmId;
  @JsonKey(name: 'farmId')
  final int farmId;
  @JsonKey(name: 'createdAt')
  final DateTime createdAt;
  @JsonKey(name: 'updatedAt')
  final DateTime updatedAt;

  final FarmModel? farm;
  final FarmModel? currentFarm;
  final BuffaloModel? father;
  final BuffaloModel? mother;
  final BuffaloModel? grandfather;
  final BuffaloModel? grandmother;
  final BuffaloModel? greatGrandfather;
  final BuffaloModel? greatGrandmother;

  @JsonKey(name: 'BuffaloImages')
  final List<dynamic> buffaloImages;
  @JsonKey(name: 'BuffaloBreedingImages')
  final List<dynamic> buffaloBreedingImages;
  @JsonKey(name: 'Histories')
  final List<dynamic> histories;

  BuffaloModel({
    required this.id,
    required this.name,
    required this.birthDate,
    required this.birthMethod,
    this.fatherId,
    this.motherId,
    this.grandfatherId,
    this.grandmotherId,
    this.greatGrandfatherId,
    this.greatGrandmotherId,
    this.currentFarmId,
    required this.farmId,
    required this.createdAt,
    required this.updatedAt,
    this.farm,
    this.currentFarm,
    this.father,
    this.mother,
    this.grandfather,
    this.grandmother,
    this.greatGrandfather,
    this.greatGrandmother,
    this.buffaloImages = const [],
    this.buffaloBreedingImages = const [],
    this.histories = const [],
  });

  factory BuffaloModel.fromJson(Map<String, dynamic> json) => _$BuffaloModelFromJson(json);
  Map<String, dynamic> toJson() => _$BuffaloModelToJson(this);
}