import 'package:buffalo_thai/model/buffalo_image_model.dart';
import 'package:buffalo_thai/model/farm_model.dart';
import 'package:json_annotation/json_annotation.dart';

part 'buffalo_model.g.dart'; // This will be generated by json_serializable

@JsonSerializable(explicitToJson: true)
class BuffaloModel {
  @JsonKey(name: 'buffaloId')
  final int id;
  @JsonKey(name: 'name', defaultValue: '')
  final String name;
  @JsonKey(name: 'birthDate')
  final DateTime? birthDate;
  @JsonKey(name: 'birthMethod', defaultValue: '')
  final String birthMethod;
  @JsonKey(name: 'fatherId')
  final int? fatherId;
  @JsonKey(name: 'motherId')
  final int? motherId;
  @JsonKey(name: 'grandfatherId')
  final int? grandfatherId;
  @JsonKey(name: 'grandmotherId')
  final int? grandmotherId;
  @JsonKey(name: 'greatGrandfatherId')
  final int? greatGrandfatherId;
  @JsonKey(name: 'greatGrandmotherId')
  final int? greatGrandmotherId;
  @JsonKey(name: 'currentFarmId')
  final int? currentFarmId;
  @JsonKey(name: 'farmId')
  final int farmId;
  @JsonKey(name: 'createdAt')
  final DateTime createdAt;
  @JsonKey(name: 'updatedAt')
  final DateTime updatedAt;

  final FarmModel? farm;
  final FarmModel? currentFarm;
  final BuffaloModel? father;
  final BuffaloModel? mother;
  final BuffaloModel? grandfather;
  final BuffaloModel? grandmother;
  final BuffaloModel? greatGrandfather;
  final BuffaloModel? greatGrandmother;

  @JsonKey(name: 'BuffaloImages', defaultValue: [])
  final List<BuffaloImageModel> buffaloImages;
  @JsonKey(name: 'BuffaloBreedingImages', defaultValue: [])
  final List<dynamic> buffaloBreedingImages; // Modify this if a specific model is needed
  @JsonKey(name: 'Histories', defaultValue: [])
  final List<dynamic> histories; // Modify this if a specific model is needed

  BuffaloModel({
    required this.id,
    required this.name,
    required this.birthMethod,
    this.birthDate,
    this.fatherId,
    this.motherId,
    this.grandfatherId,
    this.grandmotherId,
    this.greatGrandfatherId,
    this.greatGrandmotherId,
    this.currentFarmId,
    required this.farmId,
    required this.createdAt,
    required this.updatedAt,
    this.farm,
    this.currentFarm,
    this.father,
    this.mother,
    this.grandfather,
    this.grandmother,
    this.greatGrandfather,
    this.greatGrandmother,
    this.buffaloImages = const [],
    this.buffaloBreedingImages = const [],
    this.histories = const [],
  });

  factory BuffaloModel.fromJson(Map<String, dynamic> json) => _$BuffaloModelFromJson(json);
  Map<String, dynamic> toJson() => _$BuffaloModelToJson(this);
}
